# This workflow will install Python dependencies, run tests and lint with a single version of Python
name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # step 1: checkout the code form the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # step 2: setup python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # step 3: install dependencies
      - name: Install dependencies
        run: python -m pip install -r requirments.txt

      # step 4: run tests
      - name: Run tests
        run: python -m pytest

    

      
